openapi: 3.0.0

info:

  title: Jobs API

  contact: {}

  version: '1.0'

servers:

- url: https://ntl-job-api.herokuapp.com/api/v1

  variables: {}

paths:

  /auth/register:

    post:

      tags:

      - Auth

      summary: Register User

      operationId: RegisterUser

      parameters: []

      requestBody:

        description: ''

        content:

          application/json:

            schema:

              $ref: '#/components/schemas/RegisterUserRequest'

            example:

              name: Gia Huy

              password: sulachomeo

              email: giahuy123@gmail.com

        required: true

      responses:

        '200':

          description: ''

          headers: {}

      deprecated: false

      security: []

  /auth/login:

    post:

      tags:

      - Auth

      summary: Login User

      operationId: LoginUser

      parameters: []

      requestBody:

        description: ''

        content:

          application/json:

            schema:

              $ref: '#/components/schemas/LoginUserRequest'

            example:

              email: giahuy123@gmail.com

              password: sulachomeo

        required: true

      responses:

        '200':

          description: ''

          headers: {}

      deprecated: false

      security: []

  /jobs:

    get:

      tags:

      - Jobs

      summary: Get All Jobs

      operationId: GetAllJobs

      parameters: []

      responses:

        '200':

          description: ''

          headers: {}

      deprecated: false

      security:

      - bearer: []

    post:

      tags:

      - Jobs

      summary: Create Jobs

      operationId: CreateJobs

      parameters: []

      requestBody:

        description: ''

        content:

          application/json:

            schema:

              $ref: '#/components/schemas/CreateJobsRequest'

            example:

              company: Mancity

              position: Forward

              status: declined

        required: true

      responses:

        '200':

          description: ''

          headers: {}

      deprecated: false

      security:

      - bearer: []

  /jobs/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: The job Id

    get:

      tags:

      - Jobs

      summary: Get Job

      operationId: GetJob

      parameters: []

      responses:

        '200':

          description: ''

          headers: {}

      deprecated: false

      security:

      - bearer: []

    patch:

      tags:

      - Jobs

      summary: Update Job

      operationId: UpdateJob

      parameters: []

      requestBody:

        description: ''

        content:

          application/json:

            schema:

              $ref: '#/components/schemas/UpdateJobRequest'

            example:

              company: Hello Word

              status: declined

              position: Developer

        required: true

      responses:

        '200':

          description: ''

          headers: {}

      deprecated: false

      security:

      - bearer: []

    delete:

      tags:

      - Jobs

      summary: Delete Job

      operationId: DeleteJob

      parameters: []

      responses:

        '200':

          description: ''

          headers: {}

      deprecated: false

      security:

      - bearer: []

components:

  schemas:

    RegisterUserRequest:

      title: RegisterUserRequest

      required:

      - name

      - password

      - email

      type: object

      properties:

        name:

          type: string

        password:

          type: string

        email:

          type: string

      example:

        name: Gia Huy

        password: sulachomeo

        email: giahuy123@gmail.com

    LoginUserRequest:

      title: LoginUserRequest

      required:

      - email

      - password

      type: object

      properties:

        email:

          type: string

        password:

          type: string

      example:

        email: giahuy123@gmail.com

        password: sulachomeo

    CreateJobsRequest:

      title: CreateJobsRequest

      required:

      - company

      - position

      - status

      type: object

      properties:

        company:

          type: string

        position:

          type: string

        status:

          type: string

      example:

        company: Mancity

        position: Forward

        status: declined

    UpdateJobRequest:

      title: UpdateJobRequest

      required:

      - company

      - status

      - position

      type: object

      properties:

        company:

          type: string

        status:

          type: string

        position:

          type: string

      example:

        company: Hello Word

        status: declined

        position: Developer

  securitySchemes:

    bearer:

      type: http

      scheme: bearer

security: []

tags:

- name: Auth

  description: ''

- name: Jobs

  description: ''

